courses/urls.py
from django.contrib import admin
from django.conf.urls import url
from courses import views

app_name = 'courses'

urlpatterns = [
    url(r'^$', views.courses, name="courses"),
    url('python/', views.course, name="python"),
    url(r'^(?P<course_id>[0-9]+)$', views.lessons, name="lessons"),
    url('lesson/new/', views.lesson_new, name='lesson_new')
]

istudyclient/urls.py
from django.contrib import admin
from django.conf.urls import url
from base import views
from django.urls import include

app_name = 'index'

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url('main', views.index, name='index'),
    url('webinars', views.webinars, name='webinars'),
    url('courses/', include('courses.urls')),
]

repo2repo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from scrypt.views import get_repository_url, push_to_repo, edit_project, delete_project, instructions
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', LoginView.as_view(), name="login"),
    path('source/', get_repository_url, name='repos'),
    path('push/<int:id>/', push_to_repo, name='push_code'),
    path('edit/<int:pk>/', edit_project, name='edit_project'),
    path('delete/<int:pk>/', delete_project, name='delete_project'),

    path('instructions/', instructions, name='instructions'),

    path('accounts/', include('django.contrib.auth.urls')),

    path('m/', include('scrypt.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrypt/urls.py
from django.urls import path

from .views import push_to_repo

urlpatterns = [
    path('<int:id>/', push_to_repo)
]

todo/todo/todo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

base/models.py
from django.db import models


class indexPage(models.Model):
    title = models.CharField(max_length=500)
    page_context = models.TextField()

    def __str__(self):
        return self.title

base/views.py
from django.shortcuts import render
from .models import indexPage


def index(request):
    index = indexPage.objects.all()
    return render(request, "base/index.html", {'index': index})

def webinars(request):
    return render(request, "base/webinars.html")

templates/base/content.html
<h1>Позвольте представиться</h1>

<h2>iStudy</h2>

{{index.page_context}}

templates/base/courses.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>iStudy</title>
    <link rel="stylesheet" href="../../static/css/style.css">
</head>
<body>
  
    {% include "base/header.html" %}
   
<main>

    {% include "base/nav.html" %}
 
<content>
{% if courses %}
	{% for course in courses %}
		<div class="row">
			<div class="col-md-6 animate-box">
				<div class="course">
					<a href={% url 'courses:python' %} class="course-img" style="background-image: url(../../static/img/project-1.jpg);">{{course.name}}
					</a>
					<div class="desc">
						<h3><a href={% url 'courses:python' %}>{{course.name}} </a></h3>
						<p>{{course.silabus}}</p>
						<span><a href={% url 'courses:python' %} class="btn btn-primary btn-sm btn-course">Пройти курс</a></span>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}
{% else %}

no courses

{% endif %}

{% if error_message %}
	{{error_message}}
{% endif %}

</content>
</main>
</body>
</html>

templates/base/header.html
<header>
    <nav>
        <ul class="menu-main">
            <!-- <li><img src=></li> -->
            <li><a href={% url 'index' %}>iStudy</a></li>
            <li><a href="#">EVENTS</a></li>
            <li><a href="#">SEARCH</a></li>
            <li><a href="#">LOG IN/SIGHN IN</a></li>
        </ul>
    </nav>
</header>

templates/base/index.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>iStudy</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  
    {% include "base/header.html" %}
   
<main>

    {% include "base/nav.html" %}
 
<content>

    {% for page in index %}
    <div>{{page.page_context}}</div>
    {% endfor %}

</content>
</main>
</body>
</html>

templates/base/nav.html
<div class="section">
    <ul>
        <li><a href={% url 'courses:courses' %} >COURSES</a></li>
        <li><a href={% url 'webinars' %}>WEBINARS</a></li>
        <li><a href="">FORUM</a></li>
        <li><a href="">BLOG</a></li>
        <li><a href="">TESTS</a></li>
        <li><a href="">MENTORS</a></li>
        <li><a href="">VACANSES</a></li>
        <li><a href="">ABOUT US</a></li>
    </ul>
</div>

templates/base/python.html
Урок 1
Урок 2
Урок 3

templates/base/video.html
<style>
    #video12 {
      position: relative;
      padding-bottom: 50%;
    }
    #video12 iframe {
      position: absolute;
      width: calc(100% - 120px);
      height: calc(100% - 120px*3/4);
    }
    #video12 div {
      position: absolute;
      top: 0;
      right: 0;
      width: 110px;
      height: 100%;
      padding: 5px;
      overflow-y: auto;
    }
    #video12 img {
      width: calc(100% - (5px + 1px)*2);
      padding: 5px;
      border: 1px solid #555;
      border-radius: 5px;
      opacity: .7;
    }
    #video12 img:hover {
      opacity: 1;
      cursor: pointer;
    }
    #video12 img:focus {
      opacity: .2;
    }
    </style>
    
    <div id="video12">
      <iframe src="http://www.youtube.com/embed/t2MPL4Cjq6w?rel=0" allowfullscreen="" frameborder="0"></iframe>
      <div>
        <img src="http://img.youtube.com/vi/TCDfNEIc2T4/1.jpg" tabindex="2" data-start="32" data-end="60"/>
        <img src="http://img.youtube.com/vi/1tMsd7zkdhI/1.jpg" tabindex="2"/>
        <img src="http://img.youtube.com/vi/5DuSwzIJat8/1.jpg" tabindex="2"/>
        <img src="http://img.youtube.com/vi/5DuSwzIJat8/1.jpg" tabindex="2"/>
      </div>
    </div>
    
    <script>
    var IMG = document.querySelectorAll('#video12 img'),
        IFRAME = document.querySelector('#video12 iframe');
    for (var i = 0; i < IMG.length; i++) {
      IMG[i].onclick = function() {
        var idIMG = this.src.replace(/http...img.youtube.com.vi.([\s\S]*?).1.jpg/g, '$1');
        IFRAME.src = 'http://www.youtube.com/embed/' + idIMG + '?rel=0&autoplay=1';
        if(this.dataset.end) IFRAME.src = IFRAME.src.replace(/([\s\S]*)/g, '$1&end=' + this.dataset.end);
        if(this.dataset.start) IFRAME.src = IFRAME.src.replace(/([\s\S]*)/g, '$1&start=' + this.dataset.start);
        this.style.backgroundColor='#555';
      }
    }
    </script>

templates/base/webinars.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>iStudy</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  
    {% include "base/header.html" %}
   
<main>

    {% include "base/nav.html" %}
 
<content>

    <style>
        #video12 {
          position: relative;
          padding-bottom: 50%;
        }
        #video12 iframe {
          position: absolute;
          width: calc(100% - 120px);
          height: calc(100% - 120px*3/4);
        }
        #video12 div {
          position: absolute;
          top: 0;
          right: 0;
          width: 110px;
          height: 100%;
          padding: 5px;
          overflow-y: auto;
        }
        #video12 img {
          width: calc(100% - (5px + 1px)*2);
          padding: 5px;
          border: 1px solid #555;
          border-radius: 5px;
          opacity: .7;
        }
        #video12 img:hover {
          opacity: 1;
          cursor: pointer;
        }
        #video12 img:focus {
          opacity: .2;
        }
        </style>
        
        <div id="video12">
          <iframe src="http://www.youtube.com/embed/t2MPL4Cjq6w?rel=0" allowfullscreen="" frameborder="0"></iframe>
          <div>
            <img src="http://img.youtube.com/vi/TCDfNEIc2T4/1.jpg" tabindex="2" data-start="32" data-end="60"/>
            <img src="http://img.youtube.com/vi/1tMsd7zkdhI/1.jpg" tabindex="2"/>
            <img src="http://img.youtube.com/vi/5DuSwzIJat8/1.jpg" tabindex="2"/>
            <img src="http://img.youtube.com/vi/5DuSwzIJat8/1.jpg" tabindex="2"/>
          </div>
        </div>
        
        <script>
        var IMG = document.querySelectorAll('#video12 img'),
            IFRAME = document.querySelector('#video12 iframe');
        for (var i = 0; i < IMG.length; i++) {
          IMG[i].onclick = function() {
            var idIMG = this.src.replace(/http...img.youtube.com.vi.([\s\S]*?).1.jpg/g, '$1');
            IFRAME.src = 'http://www.youtube.com/embed/' + idIMG + '?rel=0&autoplay=1';
            if(this.dataset.end) IFRAME.src = IFRAME.src.replace(/([\s\S]*)/g, '$1&end=' + this.dataset.end);
            if(this.dataset.start) IFRAME.src = IFRAME.src.replace(/([\s\S]*)/g, '$1&start=' + this.dataset.start);
            this.style.backgroundColor='#555';
          }
        }
        </script>

</content>
</main>
</body>
</html>